#!/bin/bash

#------------------------------------------------------------------------------#
# For download files by specific user defnied options.
# Second bash to be executed.
# After fix_noaa

# To select year.
# To change format.

#------------------------------------------------------------------------------#
# float number comparison
function tf_1_lt_2() {
  echo "$1<$2" | bc
}

#------------------------------------------------------------------------------#
year_min=1990

#------------------------------------------------------------------------------#
FI=./WOD_fixed.csv
FO=./google.csv

rm $FO
>$FO

#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
IFS=,

i=1
tf=0
while read line; do
	
	#----------------------------------------------------------------------------#
	# read header
		
	# lat
	if [ "$i" -eq "6" ]; then
		lat="$(echo $line | sed -e "s/,//g" | sed -e "s/Latitude//g" | sed -e "s/decimal degrees//g" | sed -e "s/ //g" )"
	fi
	
	# lon
	if [ "$i" -eq "7" ]; then
		lon="$(echo $line | sed -e "s/,//g" | sed -e "s/Longitude//g" | sed -e "s/decimal degrees//g" | sed -e "s/ //g" )"
	fi
	
	# read year
	if [ "$i" -eq "8" ]; then
		year="$(echo $line | sed -e "s/,//g" | sed -e "s/Year//g" | sed -e "s/ //g" )"
		tf="$(tf_1_lt_2 "$year_min" "$year")"
		
		# year ok?
		if [ "$tf" -eq "1" ]; then
			echo $lat $lon >> $FO
		fi
		
	fi
	
	#---------------------------------------------#
	# last line of data?
	last="$(echo $line | grep -c "END OF VARIABLES SECTION")"
	if [ "$last" -eq "1" ]; then
	  i=0
	fi
	
	#---------------------------------------------#
  i=$[$i+1]
  
done < $FI



#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
exit 0





