#! /bin/bash

#------------------------------------------------------------------------------#
# For download files by region.

# To select regions.
# To change format.

#------------------------------------------------------------------------------#
# float number comparison
function tf_1_lt_2() {
  echo "$1<$2" | bc
}

#------------------------------------------------------------------------------#
lat_min=35.0
lat_max=37.5
lon_min=-10.0
lon_max=-6.0
depths_dyw=26   #2000m at least
year_min=1995

#------------------------------------------------------------------------------#
#FI=./salinity.txt
#FO=./salinity2.txt

FI=./temperature.txt
FO=./temperature2.txt


rm $FO
>$FO

#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
IFS=,

i=0
while read line; do

	if [ "$i" -gt "0" ]; then
	
	#---------------------------------------------#
  # split into an array
  field=( $line )
  
	#---------------------------------------------#
	lat=${field[2]}
	lon=${field[3]}
	year=${field[4]}
	
	tf="$(tf_1_lt_2 "$year_min" "$year")"
	if [ "$tf" -eq "1" ]; then
	tf="$(tf_1_lt_2 "$lat_min" "$lat")"
	if [ "$tf" -eq "1" ]; then
	tf="$(tf_1_lt_2 "$lat" "$lat_max")"
	if [ "$tf" -eq "1" ]; then
	tf="$(tf_1_lt_2 "$lon_min" "$lon")"
	if [ "$tf" -eq "1" ]; then
	tf="$(tf_1_lt_2 "$lon" "$lon_max")"
	if [ "$tf" -eq "1" ]; then
  	
		echo $i $lat $lon $year
		
		depths=$(( ${#field[@]} - 9 ))
		tf="$(tf_1_lt_2 "$depths_dyw" "$depths")"
		if [ "$tf" -eq "1" ]; then
		
		k=0
		for word in "${field[@]}"; do
			k=$[$k+1]
			if [ "$k" -eq "2" -o "$k" -eq "3" -o "$k" -eq "4" -o "$k" -eq "5" -o "$k" -ge "10" ]; then
			if [ "$k" -le "$[$depths_dyw+9]" ]; then
				echo -e "$word \c" >> $FO
		  fi
		  fi
		done
		
		echo "" >> $FO
		
		fi
  	
  fi
  fi
  fi
  fi
  fi
  
	#---------------------------------------------#
  fi
  i=$[$i+1]
  
done < $FI

